publishDir = "../docs"

title = "tlake.io"
baseURL = "http://tlake.io"
languageCode = "en-us"
enableGitInfo = true

theme = "ananke"
SectionPagesMenu = "main"
disqusShortname = "tannerlake"
[params]
    mainSections = ""
    github = "https://github.com/tlake"
    gitlab = "https://gitlab.com/tannerlake"
    twitter = "https://twitter.com/tanotaur"
    linkedin = "https://linkedin.com/in/tannerlake"

