baseURL = "https://tlake.io"
languageCode = "en-us"
title = "Tanner Lake"
publishDir = "../docs"
enableGitInfo = true

theme = "hermit"
markup = "markdown"

[author]
    name = "Tanner Lake"

[params]
    themeColor = "#aaaaaa"
    homeSubtitle = "Software Developer"

    [[params.social]]
        name = "email"
        url = "tanner.lake@gmail.com"

    [[params.social]]
        name = "linkedin"
        url = "https://linkedin.com/in/tannerlake"

    [[params.social]]
        name = "github"
        url = "https://github.com/tlake"

    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/tanotaur"

[menu]

    [[menu.main]]
        name = "About"
        url = "about/"
        weight = 10

    [[menu.main]]
        name = "CV"
        url = "cv/"
        weight = 15
